name: app-products-database

volumes:
  mssql-data:

networks:
  app-products-network:
    driver: bridge

services:
  products_sqlserver:
    container_name: products_sqlserver
    hostname: products_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
        - app-products-network
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPassword1234
    # env_file: sqlserver.env
